export const RANDOM_TITLES = [
  'uisque et neque vulputate, mollis ante eget, luctus ligula',
  'ras vehicula dolor gravida, dignissim ipsum at, cursus tellus',
  'liquam id sapien eleifend, congue est vitae, laoreet quam',
  'ellentesque in augue non libero aliquam congue',
  'ellentesque tristique lacus id erat finibus, viverra sagittis velit fringilla',
  'roin laoreet dolor non odio suscipit, ut hendrerit enim porttitor',
  'enean non ipsum id massa viverra consequat sed in urna',
  'ullam lobortis ante sed mollis consequat',
  'n eget ante facilisis, pulvinar ex eu, vehicula dui',
  'aecenas blandit purus blandit, dignissim nunc quis, pharetra tellus',
  'n nec tellus non orci pellentesque bibendum vel vitae lorem',
  'am porta arcu id tempus elementum',
  'urabitur laoreet eros at pharetra eleifend',
  'ullam sed est vitae ex laoreet imperdiet',
  'unc aliquet ex a nisi tincidunt varius',
  't lobortis elit eget neque accumsan pharetra',
  'usce interdum ipsum eget dolor vehicula finibus',
  'enean ut diam at odio lobortis posuere at vitae ante',
  'ed efficitur tortor vitae tortor vestibulum hendrerit',
  'liquam nec quam semper, pulvinar ligula nec, fermentum lorem',
  'ellentesque a est quis erat egestas semper',
  'nteger rutrum leo vel urna rutrum dictum',
  'n varius justo id arcu congue, non lobortis risus congue',
  't viverra tortor ac nisi ullamcorper egestas',
  'onec eu quam vel urna imperdiet aliquam at a urna',
  'am blandit nibh et hendrerit vehicula',
  'onec at lectus vitae ipsum convallis varius',
  'urabitur sed lectus non dui luctus tincidunt nec ut nisi',
  'am ut risus non eros tincidunt mattis ac a elit',
  'auris ullamcorper eros quis ex dignissim feugiat',
  'onec pulvinar dolor auctor nibh euismod, sed consectetur risus congue',
  'uisque sagittis tellus vel dapibus imperdiet',
  'uspendisse commodo quam ac diam gravida dictum',
  'liquam aliquam risus ut sem pretium, ut ultricies leo elementum',
  'hasellus pharetra nibh quis tortor lacinia, eget vehicula purus suscipit',
  'unc eget elit consequat, pretium purus eget, fringilla turpis',
  'orem ipsum dolor sit amet, consectetur adipiscing elit',
  'ras convallis nibh at justo pretium, nec varius ipsum sodales',
  'urabitur auctor lacus non sodales venenatis',
  'onec feugiat tellus nec elit bibendum, sit amet tincidunt mauris convallis',
  'ed tincidunt ligula efficitur purus egestas accumsan',
  'raesent blandit quam at risus cursus, sit amet dignissim sem lobortis',
];
